services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: toDoList
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: