basePath: /
definitions:
  models.ToDoDTO:
    properties:
      done:
        type: boolean
      id:
        type: string
      plannedDate:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API zur Verwaltung von ToDos.
  title: ToDo Inventory API
  version: "1.0"
paths:
  /todos:
    get:
      description: Gibt eine Liste aller ToDos zurück
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ToDoDTO'
            type: array
        "500":
          description: Internal Server Error
      summary: Alle ToDos abrufen
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Erstellt ein neues ToDo
      parameters:
      - description: Neues ToDo
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.ToDoDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ToDoDTO'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Neues ToDo anlegen
      tags:
      - todos
swagger: "2.0"
