basePath: /api/v1/
definitions:
  models.CreateEntryDto:
    properties:
      done:
        type: boolean
      plannedDate:
        type: string
      title:
        type: string
    type: object
  models.EntryDto:
    properties:
      done:
        type: boolean
      id:
        type: string
      plannedDate:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Life Inventory API
  version: "1.0"
paths:
  /entry:
    get:
      description: Returns a list of all entries (fitting to the filters)
      parameters:
      - description: Filter by done status
        in: query
        name: done
        type: boolean
      - description: Filter by planned date (YYYY-MM-DD)
        in: query
        name: date
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EntryDto'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all entries (with filters)
    post:
      description: Creates a new entry
      parameters:
      - description: New entry
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/models.CreateEntryDto'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.EntryDto'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create new entry
    put:
      description: Updates the entry with the given ID. The existing item will be
        completely overwritten by the provided data. The item will be identified by
        the ID of the item.
      parameters:
      - description: Updated Entry object
        in: body
        name: Entry
        required: true
        schema:
          $ref: '#/definitions/models.EntryDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EntryDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Update a entry
  /entry/{id}:
    delete:
      description: Deletes exactly one entry by ID
      parameters:
      - description: ID of the entry
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Delete a entry by ID
    get:
      description: Returns exactly one entry with the given ID
      parameters:
      - description: ID of the entry
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EntryDto'
            type: array
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get a entry by ID
  /list:
    get:
      description: Returns a list of all entries
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EntryDto'
            type: array
        "500":
          description: Internal Server Error
      summary: Get all entries
swagger: "2.0"
